import React, { useEffect, useState } from "react";
import axios from "axios";
import ImageCard from "../components/ImageCard";
import Loading from "../components/Loading";

const AllAiIMages = () => {
  const [allImages, setAllImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const limit = 9;

  const fetchImages = async (page) => {
    setLoading(true);
    axios
      .get(`http://localhost:3000/all-ai-images?page=${page}&limit=${limit}`)
      .then((data) => {
        console.log(data.data);
        setAllImages([...allImages, ...data.data.images]);
        setTotal(data.data.total);
        setLoading(false);
      })
      .catch((err) => {
        console.log(err);
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchImages(page);
  }, [page]);

  const loadMore = () => {
    if (allImages.length < total) {
      setPage((prev) => prev + 1);
    }
  };

  console.log(allImages);

  return (
    <section className="flex flex-col gap-6 my-10">
      <div className="flex flex-col items-center gap-2">
        <h2 className="text-primary text-3xl font-bold">All Ai Images</h2>
        <p className="text-gray-600">
          Explore images generated by our community.
        </p>
      </div>
      {loading ? (
        <Loading />
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {allImages.map((image, index) => (
              <ImageCard key={index} image={image} />
            ))}
          </div>
          {allImages.length < total && (
            <button
              onClick={loadMore}
              className="mt-6 bg-primary text-white px-4 py-2 rounded"
            >
              Load More
            </button>
          )}
        </>
      )}
    </section>
  );
};

export default AllAiIMages;
