import React from "react";
import ImageCard from "./ImageCard";

const LatestImages = () => {
  return (
    <section className="flex flex-col gap-6 my-10">
      <div className="flex flex-col items-center gap-2">
        <h2 className="text-primary text-3xl font-bold">Latest Creations</h2>
        <p className="text-gray-600">
          Explore images generated by our community.
        </p>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {Array.from({ length: 6 }).map((image, index) => (
          <ImageCard key={index} />
        ))}
      </div>
    </section>
  );
};

export default LatestImages;
