import React, { use, useEffect } from "react";
import ImageCard from "./ImageCard";
import axios from "axios";
import { Link } from "react-router";

const latestImagePromise = axios
  .get("http://localhost:3000/latest-images")
  .then((data) => data.data);

const LatestImages = ({ latestImg, setLatestImg }) => {
  const latestImages = use(latestImagePromise);

  useEffect(() => {
    setLatestImg(latestImages.images);
  }, [latestImages, setLatestImg]);

  return (
    <section className="flex flex-col gap-6 my-10">
      <div className="flex flex-col items-center gap-2">
        <h2 className="text-primary text-3xl font-bold">Latest Creations</h2>
        <p className="text-gray-600">
          Explore images generated by our community.
        </p>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {latestImg.slice(0, 6).map((image, index) => (
          <ImageCard key={index} image={image} />
        ))}
      </div>
      <div className="w-full flex justify-center my-4">
        <Link to="/published-image" className="btn btn-primary">
          Show All
        </Link>
      </div>
    </section>
  );
};

export default LatestImages;
